---
apiVersion: v1 
kind: Namespace 
metadata:
  name: ws3
  labels: 
    version: v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ws3-config
  namespace: ws3
data:
  db_host: mysqldb-svc
  #db_host: mysqldb-svc.ws3.svc.cluster.local
  db_user: root

---
apiVersion: v1
kind: Secret
metadata:
  name: ws3-secret
  namespace: ws3
data:
  # db_password: Reallyreallyveryveryveryseeeeeccreettttpw
  db_password: UmVhbGx5cmVhbGx5dmVyeXZlcnl2ZXJ5c2VlZWVlY2NyZWV0dHR0cHc=