---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-v1-deploy
  namespace: {{ include "nw.namespace" . }}
  labels:
    name:  app-v1-deploy
spec:
  # number of pod
  replicas: {{ .Values.replicaCount.nwserver.count }}
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name:  app-deploy
      version: v1
  template:
    metadata:
      name: app-v1-pod
      labels: 
        name: app-deploy
        version: v1
    spec:
      containers:
      - image:  "{{ .Values.image.nwserverv1.name }}:{{ .Values.image.nwserverv1.version }}"
        name:  app-v1-container
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nw-secret
                  key: db_password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: 
                  name: nw-config
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef: 
                  name: nw-config
                  key: db_user
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP   
        ports:
        - containerPort:  {{ .Values.service.port.nwserver }}
          name:  nwserver-port
---
apiVersion: v1
kind: Service
metadata:
  name: app-v1-svc
  namespace: {{ include "nw.namespace" . }}
spec:
  selector:
    name: app-deploy
    version: v1
  type: ClusterIP
  ports:
  - port: 80
    targetPort: nwserver-port
