---
apiVersion: v1 
kind: Namespace 
metadata:
  name: {{ include "nw.namespace" . }}
  labels: 
    version: {{ .Values.nw.version }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nw-config
  namespace: {{ include "nw.namespace" . }}
data:
  db_host: mysqldb-svc
  db_user: {{ .Values.db.user }}

---
apiVersion: v1
kind: Secret
metadata:
  name: nw-secret
  namespace: {{ include "nw.namespace" . }}
data:
  db_password: {{ .Values.db.password }}