---
apiVersion: v1 
kind: Namespace 
metadata:
  name: myns
  labels: 
    version: v1

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: myns
  labels:
    name: fortune
    version: v1
spec:
  # number of pod
  replicas: 3
  selector:
    matchLabels:
      name: fortune
      version: v1
  template:
    # pod template
    metadata:
      name: fortune-pod
      labels:
        name: fortune
        version: v1
    spec:
      containers:
        - name: fortune-container
          image: zytean/myfortuneapp:v2.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_PORT
              value: "3000"
          ports:
            - name: fortune-pod
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  namespace:  myns
  labels:
    name: fortune-svc
    version: v1
spec:
  type: LoadBalancer
  selector:
    name: fortune
    version: v1
  ports:
  - name: fortune-http
    port: 80
    targetPort: fortune-pod




