---
apiVersion: v1 
kind: Pod
metadata:
  name: fortune-pod
  namespace: myns
  labels:
    name: fortune
    version: v1
spec:
  containers:
    - name: fortune-container
      image: zytean/myfortuneapp:v2.0.1
      imagePullPolicy: Always
      env:
        - name: APP_PORT
          value: "3000"
      ports:
        - name: http
          containerPort: 3000