---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nwserver-deploy
  namespace: nw
  labels:
    name: nwserver-deploy
    version: v1
spec:
  # number of pod
  replicas: 6
  selector:
    matchLabels:
      name: nwserver-pod
      version: v1
  template:
    # pod template
    metadata:
      name: nwserver-pod
      labels:
        app.kubernetes.io/name: nwserver
        app.kubernetes.io/version: v1
        app.kubernetes.io/part-of: nwapp
        name: nwserver-pod
        version: v1
    spec:
      containers:
        - name: nwserver-container
          image: zytean/nwserver:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nw-secret
                  key: db_password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: 
                  name: nw-config
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef: 
                  name: nw-config
                  key: db_user
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: nwserver-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nwserver-svc
  namespace: nw
  labels:
    name: nwserver-svc
    version: v1
spec:
  type: LoadBalancer
  selector:
    name: nwserver-pod
    version: v1
  ports:
  - name: nwserver-http
    port: 80
    targetPort: nwserver-port